-- Désactiver RLS pour les tables better-auth
ALTER TABLE "users" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "accounts" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "sessions" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "verification_tokens" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "verification" DISABLE ROW LEVEL SECURITY;
